FROM python:3.9-slim AS builder

WORKDIR /monero-docs

COPY . /monero-docs

RUN pip install -r requirements.txt

RUN mkdocs build

FROM nginx:alpine

COPY --from=builder /monero-docs/public /usr/share/nginx/html

# Inline Nginx configuration
RUN echo 'server { \
    listen 80; \
    root /usr/share/nginx/html; \
    index index.html index.htm; \
    error_page 404 /404.html; \
    location = /404.html { \
        internal; \
    } \
    location / { \
        try_files $uri $uri/ =404; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
